// All balls, obstacles, plungers, etc.

import {
  Circle,
  Box,
  Line,
  Vec2,
  Plunger,
} from "../src/utils/collision_detection_lib/types";

export let boxObstacles: Box[] = [
  {
    type: "Box",
    id: 0,
    center_x: 300,
    center_y: 255,
    width: 200,
    height: 100,
  },
  {
    type: "Box",
    id: 1,
    center_x: 200,
    center_y: 505,
    width: 200,
    height: 100,
  },
  {
    type: "Box",
    id: 2,
    center_x: 1000,
    center_y: 155,
    width: 150,
    height: 150,
  },
  {
    type: "Box",
    id: 3,
    center_x: 800,
    center_y: 555,
    width: 180,
    height: 80,
  },
  {
    type: "Box",
    id: 4,
    center_x: 600,
    center_y: 200,
    width: 100,
    height: 50,
  },
  {
    type: "Box",
    id: 5,
    center_x: 1100,
    center_y: 400,
    width: 80,
    height: 80,
  },
  {
    type: "Box",
    id: 6,
    center_x: 400,
    center_y: 100,
    width: 120,
    height: 60,
  },
];

export let circleObstacles: Circle[] = [
  {
    type: "Circle",
    id: 0,
    center_x: 1050,
    center_y: 550,
    radius: 25,
  },
  {
    type: "Circle",
    id: 1,
    center_x: 850,
    center_y: 350,
    radius: 100,
  },
  {
    type: "Circle",
    id: 2,
    center_x: 650,
    center_y: 350,
    radius: 20,
  },
  {
    type: "Circle",
    id: 3,
    center_x: 680,
    center_y: 370,
    radius: 15,
  },
  {
    type: "Circle",
    id: 4,
    center_x: 1200,
    center_y: 100,
    radius: 30,
  },
  {
    type: "Circle",
    id: 5,
    center_x: 300,
    center_y: 600,
    radius: 40,
  },
  {
    type: "Circle",
    id: 6,
    center_x: 750,
    center_y: 150,
    radius: 25,
  },
  {
    type: "Circle",
    id: 7,
    center_x: 500,
    center_y: 450,
    radius: 15,
  },
  {
    type: "Circle",
    id: 8,
    center_x: 1000,
    center_y: 300,
    radius: 20,
  },
];

export let lineObstacles: Line[] = [
  {
    type: "Line",
    id: 0,
    x1: 500,
    x2: 600,
    y1: 100,
    y2: 500,
  },
  {
    type: "Line",
    id: 1,
    x1: 800,
    x2: 700,
    y1: 100,
    y2: 500,
  },
  {
    type: "Line",
    id: 2,
    x1: 600,
    x2: 550,
    y1: 500,
    y2: 600,
  },
  {
    type: "Line",
    id: 3,
    x1: 700,
    x2: 750,
    y1: 500,
    y2: 600,
  },
];

export let balls: Circle[] = [
  {
    type: "Circle",
    id: 0,
    center_x: 20,
    center_y: 590,
    radius: 6,
    velocity: { x: 0, y: -22 } as Vec2,
    acceleration: { x: 0, y: 0.2 } as Vec2,
  },
  {
    type: "Circle",
    id: 1,
    center_x: 24,
    center_y: 600,
    radius: 6,
    velocity: { x: 0, y: -22 } as Vec2,
    acceleration: { x: 0, y: 0.2 } as Vec2,
  },
  {
    type: "Circle",
    id: 6,
    center_x: 17,
    center_y: 610,
    radius: 6,
    velocity: { x: 0, y: -22 } as Vec2,
    acceleration: { x: 0, y: 0.2 } as Vec2,
  },
  {
    type: "Circle",
    id: 3,
    center_x: 18,
    center_y: 620,
    radius: 6,
    velocity: { x: 0, y: -22 } as Vec2,
    acceleration: { x: 0, y: 0.2 } as Vec2,
  },
  {
    type: "Circle",
    id: 4,
    center_x: 23,
    center_y: 630,
    radius: 6,
    velocity: { x: 0, y: -22 } as Vec2,
    acceleration: { x: 0, y: 0.2 } as Vec2,
  },
  {
    type: "Circle",
    id: 5,
    center_x: 1260,
    center_y: 590,
    radius: 6,
    velocity: { x: 0, y: -22 } as Vec2,
    acceleration: { x: 0, y: 0.2 } as Vec2,
  },
  {
    type: "Circle",
    id: 6,
    center_x: 1263,
    center_y: 600,
    radius: 6,
    velocity: { x: 0, y: -22 } as Vec2,
    acceleration: { x: 0, y: 0.2 } as Vec2,
  },
  {
    type: "Circle",
    id: 7,
    center_x: 1266,
    center_y: 610,
    radius: 6,
    velocity: { x: 0, y: -22 } as Vec2,
    acceleration: { x: 0, y: 0.2 } as Vec2,
  },
  {
    type: "Circle",
    id: 8,
    center_x: 1269,
    center_y: 620,
    radius: 6,
    velocity: { x: 0, y: -22 } as Vec2,
    acceleration: { x: 0, y: 0.2 } as Vec2,
  },
  {
    type: "Circle",
    id: 9,
    center_x: 1272,
    center_y: 630,
    radius: 6,
    velocity: { x: 0, y: -22 } as Vec2,
    acceleration: { x: 0, y: 0.2 } as Vec2,
  },
];

export const plungers: Plunger[] = [
  {
    shaft: {
      type: "Box",
      id: 0,
      center_x: 30,
      center_y: 660,
      width: 20,
      height: 60,
    },
    knob: {
      type: "Circle",
      id: 1,
      center_x: 30,
      center_y: 630,
      radius: 15,
    },
    color: "red",
  },
  {
    shaft: {
      type: "Box",
      id: 2,
      center_x: 1270,
      center_y: 660,
      width: 20,
      height: 60,
    },
    knob: {
      type: "Circle",
      id: 3,
      center_x: 1270,
      center_y: 630,
      radius: 15,
    },
    color: "red",
  },
];
